import '../../public/vendor/jquery/jquery.min.js'
import '../../public/vendor/slick/slick.min.js'
import '../../public/vendor/bootstrap/js/bootstrap.min.js'
import '../../public/@raven/animations/js/index.js'
import '../config/index.js'